### ISSUE TITLE
como testar o plugins?

### ISSUE THREAD

**Issue by marcelowu** [matheus-gio/CieloBagisto#1]
instalei coloquei MerchantKey de teste, mas ta erro.
![Captura de tela de 2020-11-01 23-08-44](https://user-images.githubusercontent.com/30912144/97823300-4d73b480-1c97-11eb-9b53-29b7f4708109.png)

**Comment by matheus-gio** [comment]
Olá, tudo bem?
Enviei uma atualização de alguns erros, se puder por gentileza atualizar e me der um feedback.
Aguardo seu retorno 👍

**Comment by marcelowu** [comment]
testei com novo plugins, mas continua com error

![Captura de tela de 2020-11-02 16-06-33](https://user-images.githubusercontent.com/30912144/97908529-98d4a400-1d25-11eb-9e0c-e8deb4096892.png)

**Comment by matheus-gio** [comment]
Você está utilizando o merchant id ? e configurou as 4 linhas no endereço na ordem : endereço, número, complemento, bairro

**Comment by marcelowu** [comment]
sim
